"""
Regression tests on the bundled PBMC toy dataset.

Golden values are pinned directly in _PINNED_GOLDEN below — they are NOT
auto-generated.  This prevents silent self-validation: if the algorithm
changes and tests are re-run, the tests will fail until a developer
consciously updates the pinned values here AND in regression_golden.json.

LIMITATION — these are Python self-consistency tests, not R validation:
  The pinned values were produced by this Python implementation, not by the
  R SoupX package.  They catch algorithmic drift within the Python codebase
  but do not guarantee agreement with R.  See validate_hgmm.py and
  test_validate_hgmm.py for a benchmark with an external ground truth.

To regenerate after an intentional algorithm change:
  1. Delete tests/regression_golden.json.
  2. Run pytest — TestAaGenerateGolden will recreate the JSON.
  3. Update _PINNED_GOLDEN below to match the new JSON values.
  4. Commit both changes together with an explanation.

Tolerances: 5% relative for rho (was 20% — tightened to catch real drift),
            5% for soup profile fractions.
"""

import json
import os

import numpy as np
import pandas as pd
import pytest

TOYDATA_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), '..', 'datasets', 'toyData')
)
GOLDEN_PATH = os.path.join(os.path.dirname(__file__), 'regression_golden.json')

# ── Pinned golden values (update deliberately, never auto-generate) ───────────
# Generated by this Python implementation on the committed toyData PBMC dataset.
_PINNED_GOLDEN = {
    'soup_top5_genes':     ['LTB', 'LDHB', 'IL32', 'CD3D', 'CD3E'],
    'soup_top5_est':       [0.06620929167243712, 0.039480552685125014,
                            0.03887332346141964, 0.030553217782228425,
                            0.02637718522621952],
    'rho_global':          0.068,
    'n_usable_estimates':  4,
    'n_cells':             62,
    'n_genes':             226,
}


# ── helpers ───────────────────────────────────────────────────────────────────

def _load_golden():
    if not os.path.exists(GOLDEN_PATH):
        return {}
    with open(GOLDEN_PATH) as f:
        return json.load(f)


def _save_golden(data: dict) -> None:
    existing = _load_golden()
    existing.update(data)
    with open(GOLDEN_PATH, 'w') as f:
        json.dump(existing, f, indent=2)


# ── module-scoped fixtures (pipeline runs once per test session) ──────────────

@pytest.fixture(scope="module")
def toy_sc():
    if not os.path.isdir(TOYDATA_DIR):
        pytest.skip(f"Toy dataset not found: {TOYDATA_DIR}")
    from SoupX.io import load_10x
    return load_10x(TOYDATA_DIR, verbose=False)


@pytest.fixture(scope="module")
def toy_sc_clustered(toy_sc):
    from SoupX import set_clusters
    meta_path = os.path.join(TOYDATA_DIR, 'metaData.tsv')
    meta = pd.read_csv(meta_path, sep='\t', index_col=0)
    clusters = meta['res.1'].astype(str).reindex(toy_sc.cells).fillna('0')
    return set_clusters(toy_sc, clusters)


@pytest.fixture(scope="module")
def toy_sc_fit(toy_sc_clustered):
    from SoupX import auto_est_cont
    return auto_est_cont(
        toy_sc_clustered,
        do_plot=False,
        verbose=False,
        force_accept=True,
    )


# ── golden generation (only runs when regression_golden.json is absent) ───────

class TestAaGenerateGolden:
    """
    Re-creates regression_golden.json when it is absent.  Always passes.

    After regenerating, you MUST also update _PINNED_GOLDEN above so the
    actual regression tests check the new values.
    """

    def test_generate(self, toy_sc, toy_sc_fit):
        if os.path.exists(GOLDEN_PATH):
            return

        top5 = toy_sc.soup_profile.nlargest(5, 'est')
        rho = float(toy_sc_fit.meta_data['rho'].iloc[0])
        dd = toy_sc_fit.fit['dd']
        n_usable = int(dd['useEst'].sum())

        _save_golden({
            'soup_top5_genes': top5.index.tolist(),
            'soup_top5_est': top5['est'].tolist(),
            'rho_global': rho,
            'n_usable_estimates': n_usable,
            'n_cells': len(toy_sc.cells),
            'n_genes': len(toy_sc.genes),
        })


# ── structural sanity (dataset-level, no golden needed) ──────────────────────

class TestToyDataStructure:
    def test_cell_count(self, toy_sc):
        assert len(toy_sc.cells) == 62

    def test_gene_count(self, toy_sc):
        assert len(toy_sc.genes) == 226

    def test_drop_count(self, toy_sc):
        assert len(toy_sc.n_drop_umis) == 1289

    def test_soup_profile_sums_to_one(self, toy_sc):
        assert np.isclose(toy_sc.soup_profile['est'].sum(), 1.0, atol=1e-9)

    def test_no_negative_soup_fractions(self, toy_sc):
        assert (toy_sc.soup_profile['est'] >= 0).all()

    def test_cell_umis_positive(self, toy_sc):
        assert (toy_sc.meta_data['nUMIs'] > 0).all()

    def test_four_clusters(self, toy_sc_clustered):
        n_clusters = toy_sc_clustered.meta_data['clusters'].nunique()
        assert n_clusters == 4

    def test_fit_present(self, toy_sc_fit):
        assert toy_sc_fit.fit is not None
        assert 'dd' in toy_sc_fit.fit
        assert 'rho_est' in toy_sc_fit.fit

    def test_fit_dd_columns(self, toy_sc_fit):
        dd = toy_sc_fit.fit['dd']
        for col in ('gene', 'cluster', 'useEst', 'rhoEst', 'obsCnt', 'expCnt'):
            assert col in dd.columns, f"dd missing column: {col}"

    def test_at_least_one_usable_estimate(self, toy_sc_fit):
        assert toy_sc_fit.fit['dd']['useEst'].sum() > 0

    def test_rho_plausible_range(self, toy_sc_fit):
        rho = float(toy_sc_fit.meta_data['rho'].iloc[0])
        assert 0.001 <= rho <= 0.80, f"rho={rho:.4f} outside plausible PBMC range"

    def test_adjust_counts_reduces_total(self, toy_sc_fit):
        from SoupX import adjust_counts
        out = adjust_counts(toy_sc_fit, clusters=False)
        assert out.sum() < toy_sc_fit.toc.sum()

    def test_adjust_counts_non_negative(self, toy_sc_fit):
        from SoupX import adjust_counts
        out = adjust_counts(toy_sc_fit, clusters=False)
        assert out.toarray().min() >= -1e-9

    def test_adjust_counts_preserves_shape(self, toy_sc_fit):
        from SoupX import adjust_counts
        out = adjust_counts(toy_sc_fit, clusters=False)
        assert out.shape == toy_sc_fit.toc.shape

    def test_rho_uniform_default(self, toy_sc_fit):
        """Default auto_est_cont (cell_level_rho=False): all cells share same rho."""
        rhos = toy_sc_fit.meta_data['rho'].values
        # All values identical; machine epsilon noise in numpy std is acceptable.
        assert rhos.std() < 1e-10


# ── golden-value regressions (detect algorithmic drift) ──────────────────────

class TestGoldenRegression:
    """
    Numeric regression against _PINNED_GOLDEN (hard-coded above, not auto-generated).

    Tolerances: 5% relative for rho (tightened from 20%), 5% for soup fractions.
    These catch meaningful algorithmic drift while absorbing floating-point noise.

    NOTE: These are Python self-consistency tests.  They verify the algorithm
    has not drifted from a previously accepted Python output.  They do NOT
    validate agreement with the R SoupX reference implementation.
    See test_validate_hgmm.py for an external-ground-truth benchmark.
    """

    def test_soup_top5_gene_identity(self, toy_sc):
        top5 = toy_sc.soup_profile.nlargest(5, 'est')
        assert top5.index.tolist() == _PINNED_GOLDEN['soup_top5_genes'], (
            f"Top-5 soup genes changed.\n"
            f"  got:      {top5.index.tolist()}\n"
            f"  expected: {_PINNED_GOLDEN['soup_top5_genes']}\n"
            "Update _PINNED_GOLDEN if this change is intentional."
        )

    def test_soup_top5_fractions(self, toy_sc):
        top5 = toy_sc.soup_profile.nlargest(5, 'est')
        np.testing.assert_allclose(
            top5['est'].values,
            _PINNED_GOLDEN['soup_top5_est'],
            rtol=0.05,
            err_msg="Soup profile fractions drifted >5% from pinned golden.",
        )

    def test_global_rho(self, toy_sc_fit):
        rho = float(toy_sc_fit.meta_data['rho'].iloc[0])
        assert rho == pytest.approx(_PINNED_GOLDEN['rho_global'], rel=0.05), (
            f"Global rho drifted >5% from pinned golden.\n"
            f"  got:     {rho:.6f}\n"
            f"  pinned:  {_PINNED_GOLDEN['rho_global']:.6f}\n"
            "Update _PINNED_GOLDEN['rho_global'] if this change is intentional."
        )

    def test_n_usable_estimates(self, toy_sc_fit):
        n = int(toy_sc_fit.fit['dd']['useEst'].sum())
        expected = _PINNED_GOLDEN['n_usable_estimates']
        assert abs(n - expected) <= max(2, int(0.10 * expected)), (
            f"Number of usable estimates changed: got {n}, pinned {expected}\n"
            "Update _PINNED_GOLDEN['n_usable_estimates'] if this change is intentional."
        )
