blank_issues_enabled: false
contact_links:
  - name: Discussion / Question
    url: https://github.com/IsratIJK/Upgraded-soupX/discussions
    about: For general usage questions, please use GitHub Discussions.
